package io.github.joshuamatosdev.security.edge;

import static org.springframework.security.test.web.reactive.server.SecurityMockServerConfigurers.mockOAuth2Login;

import io.github.joshuamatosdev.security.edge.headers.SecurityHeadersFilter;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.webtestclient.autoconfigure.AutoConfigureWebTestClient;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.context.ApplicationContext;
import org.springframework.security.core.authority.SimpleGrantedAuthority;
import org.springframework.test.web.reactive.server.WebTestClient;

/**
 * Proves the security headers reach <em>real</em> responses, including ones generated by Spring
 * Security itself. The filter runs at HIGHEST_PRECEDENCE and writes in {@code beforeCommit}, so the
 * headers must appear on both a 200 from a controller and a 403 the authorization layer produces —
 * not just proxied responses. The detailed HSTS conditional matrix is unit-tested separately in
 * {@code headers.SecurityHeadersFilterTest}.
 *
 * <p>Why this is important to test: the edge is the first externally reachable request boundary,
 * so regressions become observable access-control behavior.
 */
@SpringBootTest
@AutoConfigureWebTestClient
class SecurityHeadersTest {

  @Autowired private ApplicationContext context;

  private WebTestClient webClient;

  @BeforeEach
  void bindClientToSpringSecurity() {
    webClient = SecuredWebTestClients.bindTo(context);
  }

  @Test
  void coreSecurityHeadersPresentOnPublicResponse() {
    webClient
        .get()
        .uri("/api/public/status")
        .exchange()
        .expectStatus()
        .isOk()
        .expectHeader()
        .valueEquals(
            SecurityHeadersFilter.X_CONTENT_TYPE_OPTIONS_HEADER,
            SecurityHeadersFilter.X_CONTENT_TYPE_OPTIONS_VALUE)
        .expectHeader()
        .valueEquals(
            SecurityHeadersFilter.X_FRAME_OPTIONS_HEADER,
            SecurityHeadersFilter.X_FRAME_OPTIONS_VALUE)
        .expectHeader()
        .valueEquals(
            SecurityHeadersFilter.CONTENT_SECURITY_POLICY_HEADER,
            SecurityHeadersFilter.CONTENT_SECURITY_POLICY_VALUE)
        .expectHeader()
        .valueEquals(
            SecurityHeadersFilter.REFERRER_POLICY_HEADER,
            SecurityHeadersFilter.REFERRER_POLICY_VALUE)
        .expectHeader()
        .valueEquals(
            SecurityHeadersFilter.PERMISSIONS_POLICY_HEADER,
            SecurityHeadersFilter.PERMISSIONS_POLICY_VALUE);
  }

  @Test
  void coreSecurityHeadersPresentOnSecurityGeneratedForbidden() {
    webClient
        .mutateWith(mockOAuth2Login().authorities(new SimpleGrantedAuthority("ROLE_auditor")))
        .get()
        .uri("/api/admin/dashboard")
        .exchange()
        .expectStatus()
        .isForbidden()
        .expectHeader()
        .valueEquals(
            SecurityHeadersFilter.X_CONTENT_TYPE_OPTIONS_HEADER,
            SecurityHeadersFilter.X_CONTENT_TYPE_OPTIONS_VALUE)
        .expectHeader()
        .valueEquals(
            SecurityHeadersFilter.CONTENT_SECURITY_POLICY_HEADER,
            SecurityHeadersFilter.CONTENT_SECURITY_POLICY_VALUE);
  }

  @Test
  void hstsEmittedOnPlainHttpByDefault() {
    // The reference app defaults edge.hsts.unconditional=true so a stripped proxy header cannot
    // silently suppress transport pinning.
    webClient
        .get()
        .uri("/api/public/status")
        .exchange()
        .expectStatus()
        .isOk()
        .expectHeader()
        .valueEquals(
            SecurityHeadersFilter.STRICT_TRANSPORT_SECURITY_HEADER,
            SecurityHeadersFilter.STRICT_TRANSPORT_SECURITY_VALUE);
  }

  @Test
  void hstsEmittedWhenForwardedProtoIsHttps() {
    webClient
        .get()
        .uri("/api/public/status")
        .header("X-Forwarded-Proto", "https")
        .exchange()
        .expectStatus()
        .isOk()
        .expectHeader()
        .valueEquals(
            SecurityHeadersFilter.STRICT_TRANSPORT_SECURITY_HEADER,
            SecurityHeadersFilter.STRICT_TRANSPORT_SECURITY_VALUE);
  }
}
