crypto:
  default-algorithm: EdDSA
  default-key-id: local-ed25519-1
  local-ephemeral-keys:
    enabled: true
  providers:
    jca:
      ed25519:
        enabled: true
      ecdsa-p256:
        enabled: false
